//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by OD3.rc
//
#define IDD_ABOUTBOX                    100
#define ID_INDICATOR_MSG                101
#define ID_INDICATOR_PROGRESS           102
#define IDC_PROGRESS                    103
#define IDR_MAINFRAME                   128
#define IDR_OD3TYPE                     129
#define IDD_NEW_PROJECT                 130
#define IDD_PROJECT_OPTIONS_DIALOG      131
#define IDD_ASSOCIATIONS_PAGE           132
#define IDB_FILE_CLOSED                 133
#define IDD_INPUTFILES_PAGE             133
#define IDB_FILE_OPEN                   134
#define IDD_MANUALINPUT_PAGE            134
#define IDD_OUTPUTFILES_PAGE            135
#define IDD_PROCESSING_PAGE             136
#define IDD_ACC_DIALOG                  137
#define IDD_MANUAL_BEAM_INPUT           139
#define IDB_BEAM                        141
#define IDB_BEAM_SELECTED               142
#define IDB_ACC                         143
#define IDB_ACC_SELECTED                144
#define IDD_REPORTS_PAGE                151
#define IDD_SELECT_ITEMS_DIALOG         152
#define IDR_POPUPMENUS                  152
#define IDB_SMALLBEAM                   152
#define IDD_ITEMS_LIST_DIALOG           153
#define IDR_LEFTPOPUP                   153
#define IDD_DIALOG1                     156
#define IDB_LOGO                        158
#define IDR_SYSASS_POP                  160
#define IDD_CEE_SECTION                 161
#define IDD_LISTACC                     162
#define IDD_SPLITD3                     163
#define IDB_CHILD                       164
#define IDB_PRINT_SEL                   166
#define IDD_SPLASH                      167
#define IDB_SPLASH                      168
#define IDB_MAINTOOL                    169
#define IDD_WHATSNEW                    170
#define IDD_WERNIK                      171
#define IDB_QMARK                       172
#define IDD_MESSAGE                     173
#define IDD_UPDATECOILSTATUS            174
#define IDC_RADIO_PROJTYPE1             1000
#define IDC_BEAM_REF                    1000
#define IDC_RADIO_PROJTYPE2             1001
#define IDC_PROJECT_SETUP_BUTTON        1001
#define IDC_ADD_EXTRA_BEAM              1001
#define IDC_RADIO_PROJTYPE3             1002
#define IDC__COMBO_OUTPUT_LINE          1002
#define IDC_EDIT_PROJNAME               1003
#define IDC_RADIO_PROCESS_ALL           1003
#define IDC_EDIT_CUSTOMER_NAME          1004
#define IDC_RADIO_SELECT_FILES          1004
#define IDC_EB_SLOPE                    1004
#define IDC_STATIC_VERSION              1004
#define IDC_EDIT_CUSTOMER_REF           1005
#define IDC_RADIO_PROCESS_AUTO          1005
#define IDC_EDIT_OHANG2                 1005
#define IDC_REPORT_PRODLINE             1005
#define IDC_EDIT_JOB_DESTINATION        1006
#define IDC_COMBO_PRODUCTS              1006
#define IDC_COMBO_PROFILE               1006
#define IDC_SELECT_ACC_BUTTON           1006
#define IDC_REPORT_LIST                 1006
#define IDC_DUEDATE_MONTHCALENDAR       1007
#define IDC_OUPUT_ADD_BUTTON            1007
#define IDC_RADIO_MTYPE1                1007
#define IDC_SELECT_BEAM_BUTTON          1007
#define IDC_AUTOPATH_BUTTON             1007
#define IDC_COMBO_PRODUCTNAMES          1007
#define IDC_EDIT_DUEDATE                1008
#define IDC_OUTPUT_REMOVE_BUTTON        1008
#define IDC_RADIO_MTYPE2                1008
#define IDC_PROJPATH_BUTTON             1008
#define IDC_OUTPUT_LIST                 1009
#define IDC_EDIT_MARK                   1009
#define IDC_EDIT_DRAWN_BY               1009
#define IDC_EDIT_COMMENTS               1009
#define IDC_EDIT_AUTOLINES              1010
#define IDC_EDIT_QTY                    1010
#define IDC_APPLY_ITEM_NO               1010
#define IDC_SELECT_OUTPATH_BUTTON       1010
#define IDC_EDIT_NONAUTOLINES           1011
#define IDC_EDIT_LENGTH                 1011
#define IDC_SELECT_ITEMID_SPIN          1011
#define IDC_AUTOINPUT                   1012
#define IDC_EDIT_BDL_COUNT              1012
#define IDC_ITEMS_LIST                  1012
#define IDC_REPORTS_ADD_BUTTON          1012
#define IDC_RADIO_OPTIONS_PROMPT        1013
#define IDC_EDIT_OHANG1                 1013
#define IDC_REPORTS_REMOVE_BUTTON       1013
#define IDC_COMBO_PRODLINE              1014
#define IDC_ITEM_LABEL                  1014
#define IDC_SELECT_ITEM                 1014
#define IDC_REPORTS_AUTO_BUTTON         1014
#define IDC_RADIO_PRODUCTGROUP          1015
#define IDC_EDIT_SPAN1                  1015
#define IDC_REPORTS_NONAUTO_BUTTON      1015
#define IDC_RADIO_SECTION_TYPE          1016
#define IDC_EDIT_SPAN2                  1016
#define IDC_RADIO_PRODUCT               1017
#define IDC_EDIT_SPAN3                  1017
#define IDC_ASSOCIATE_BUTTON            1018
#define IDC_COMBO_SPC                   1018
#define IDC_REMOVE_BUTTON               1019
#define IDC_EXTRA_HOLE_GRID             1019
#define IDC_ASSOCIATION_LIST            1020
#define IDC_EDIT_ITEM_NO                1020
#define IDC_PROJECTDIR                  1021
#define IDC_ITEM_NO_SPIN                1021
#define IDC_JR_PRODUCTS                 1021
#define IDC_EDIT_OUTPUT_PATH            1023
#define IDC_PREVIOUS__BUTTON            1023
#define IDC_SBE_PRODUCTS                1023
#define IDC_NEXT_BUTTON                 1024
#define IDC_STANDARD_PRODUCTS           1024
#define IDC_SAVE_BUTTON                 1025
#define IDC_COMBO_PRODUCTCODES          1025
#define IDC_ADDITEM_BUTTON              1026
#define IDC_DELETE_BEAM                 1027
#define IDC_BUILD                       1028
#define IDC_BUTTON1                     1029
#define IDC_EDIT1                       1030
#define IDC_EDIT2                       1031
#define IDC_EDIT3                       1032
#define IDC_BUTTON2                     1033
#define IDC_BUTTON3                     1034
#define IDC_FAILLIST                    1035
#define IDC_TEXT                        1036
#define IDC_DEL_ITEM                    1037
#define IDC_ACC_LIST                    1039
#define IDC_PRINT_ACC                   1040
#define IDC_WARLEY_RAD                  1041
#define IDC_IRVINE_RAD                  1042
#define IDC_EXPORTWARLEY                1043
#define IDC_EXPORTIRVINE                1044
#define IDC_PRINTEXPORTS                1045
#define IDC_EXPORTPRODUCTS_TREE         1046
#define IDC_ACC_NAME                    1051
#define IDC_ACC_QTY                     1052
#define IDC_ACC_LEN                     1053
#define IDC_ACC_MARK                    1054
#define IDC_ACC_BUNDLE                  1055
#define IDC_ACC_COMMENT                 1056
#define IDC_ACC_PREV                    1057
#define IDC_ACC_NEXT                    1058
#define IDC_ACC_SAVE                    1060
#define IDC_ACC_NEW                     1061
#define IDC_ANIMATEOD3                  1062
#define IDC_ANIMATEOD3_A                1063
#define IDC_DONTSHOW                    1064
#define IDC_DISPLAYTEXT                 1065
#define IDC_ISWERNIK                    1066
#define IDC_NOTWERNIK                   1067
#define IDC_MESSAGEPOINT                1068
#define IDC_ASFSERVICE                  1069
#define IDC_LIST_FAULTS                 1071
#define IDC_COIL_JOBNUM                 1073
#define IDC_COIL_JOBLIST                1074
#define IDC_COIL_JOBSERACH              1075
#define IDC_COIL_ORDERNUM               1076
#define ID_PROCESS_ADD                  32771
#define ID_ADD_NEWITEM                  32772
#define ID_DB_CONNECT                   32776
#define ID_DB_DISCONNECT                32777
#define ID_OPEN_SYSCONFIG               32778
#define ID_PROCESS_VALIDATE             32779
#define ID_PROCESS_GENERATE             32780
#define ID_FILE_IMPORT_D3               32784
#define ID_FILE_IMPORT_PROJECTSETTINGS  32785
#define ID_PROCESS_ADD_NEWITEM          32786
#define ID_PROCESS_ADD_NEWBEAM          32787
#define ID_PRINT_BEAM                   32789
#define ID_PRINT_ACCESSORY              32790
#define ID_PROCESS_DELETE_BEAM          32791
#define ID_PROCESS_ADD_NEWACCESSORY     32793
#define ID_PROCESS_VALIDATE_ALL         32794
#define ID_PROCESS_VALIDATE_ITEM        32795
#define ID_PROCESS_GENERATE_ITEM        32796
#define ID_PROCESS_GENERATE_ALL         32797
#define ID_PROCESS_DELETE_ITEM          32799
#define ID_PROCESS_DELETE_ACCESSORY     32801
#define ID_DELETEITEM                   32802
#define ID_DELETE_ELEMENT               32803
#define ID_FILE_TRANSFER                32805
#define ID_PROCESS_PRINT_ALL            32806
#define ID_PROCESS_PRINT_ITEM           32807
#define ID_ITEM_GENERATE                32808
#define ID_PROCESS_PRINT_THIS           32809
#define ID_EDIT_ELEMENT                 32810
#define ID_ELEMENT_DELETE               32811
#define ID_ELEMENT_EDIT                 32812
#define ID_ITEM_ADD_BEAM                32813
#define ID_ITEM_TRANSFER                32814
#define ID_ITEM_VALIDATE                32815
#define ID_ITEM_PRINT                   32816
#define ID_ELEMENT_CUT                  32818
#define ID_ELEMENT_COPY                 32819
#define ID_ELEMENT_PASTE                32820
#define ID_ITEM_DELETE                  32822
#define ID_DUMP_SETREPORTTYPE_ALLITEMS  32823
#define IDM_SELECTALLITEMS              32824
#define IDT_STANDARD_TEMP               32825
#define IDT_STANDARD_TEMP_LOAD          32826
#define IDM_PRINTTHISELEMENT            32827
#define IDM_SYS_SELALL                  32828
#define IDM_SYS_DEL                     32829
#define IDM_IMPORT_ASW                  32830
#define IDM_ADVANCED_MODE               32831
#define IDM_VAL_SELECTION               32832
#define IDM_GEN_SELECTION               32833
#define IDM_REP_SELECTION               32834
#define IDM_TRAN_SELECTION              32835
#define IDM_EXPORT_D3                   32837
#define IDS_NOSERVICEFAULT              32838
#define IDM_PRINT_SUMMARY               32839
#define IDS_MISSINGCOILPATH             32839
#define IDM_PRINT_JOBSHEETS             32840
#define IDM_COIL_SENDJOB                32841
#define IDM_COIL_UPDATEJOB              32842
#define IDM_COIL_PRINTLIVE              32843
#define IDM_COIL_EXPORTLIVE             32844
#define IDS_DEL_ITEM                    50446
#define IDS_DEL_ONE_ELEMENT             50447
#define IDS_DEL_ELEMENTS                50448
#define IDS_FILE_MISSING                50449
#define IDS_PART1                       50451
#define IDS_PART2                       50452
#define IDS_PART3                       50453
#define IDS_PART4                       50454
#define IDS_PART5                       50455
#define IDS_PART6                       50456
#define IDS_PART7                       50457
#define IDS_PART8                       50458
#define IDS_PART9                       50459
#define IDS_PART10                      50460
#define IDS_PART11                      50461
#define IDS_PUNCH_SETTING_WARN          50462
#define IDS_PRINTFOOT                   50463
#define IDS_MISSINGCONFIG               50464
#define IDS_PUNCH_ERROR                 50465
#define IDS_SOFTWARE_VERSION            50466
#define IDS_DELASSO                     50467
#define IDS_HELPFAIL                    50468
#define IDS_PUNCH_FAIL                  50469
#define IDS_MANUAL_CODE_WARNING         50470
#define IDS_PUNCHCOMMENTWARN            50471
#define IDS_SD_CUSTNAME                 50472
#define IDS_SD_ORDERNUM                 50473
#define IDS_SD_BEAMCOUNT                50474
#define IDS_SD_TYPE                     50475
#define IDS_SD_BEAM                     50476
#define IDS_SD_MARK                     50477
#define IDS_SD_LEN_PUNCH                50478
#define IDS_SD_BEAM_TYPE                50479
#define IDS_SD_QUANTITY                 50480
#define IDS_SD_ACC                      50481
#define IDS_SD_TYPE2                    50482
#define IDS_SD_HOLE_ROUND               50483
#define IDS_SD_HOLE_SQUARE              50484
#define IDS_SD_HOLE_FLANGE              50485
#define IDS_SD_HOLE_ALL4                50486
#define IDS_SD_HOLE_TOP                 50487
#define IDS_SD_HOLE_BOTTOM              50488
#define IDS_SD_HOLE_TOPFLANGE           50489
#define IDS_SD_HOLE_BOTTOMFLANGE        50490
#define IDS_SD_COMMENTS                 50491
#define IDS_SD_LEN_NOPUNCH              50492
#define IDS_SD_CUTMARK                  50493
#define IDS_SD_PRINTTITLE               50494
#define IDS_SD_PRINTWARN                50495
#define IDS_DEL_ONE                     50496
#define IDS_DEL_MANY                    50497
#define IDS_GENERATED                   50498
#define IDS_MEDIANOTCLEAN               50499
#define IDS_WARNDIRTY                   50500
#define IDS_NOT_EXPORTED_IRVINE         50501
#define IDS_NOT_PRINTED                 50502
#define IDS_NOT_EXPORTED_WARLEY         50503
#define IDS_DAVACCESSORIES              50504
#define IDS_DISKREADONLY                50505
#define IDS_DISKMISSING                 50506
#define IDS_PRODUCTMISS                 50507
#define IDS_BEAMPASTE                   50508
#define IDS_ACCESSORYPASTE              50509
#define IDS_NOMARK                      50510
#define IDS_NOBUNDLE                    50511
#define IDS_NOLENGTH                    50512
#define IDS_NOQUANTITY                  50513
#define IDS_ACCESSORYCHANGED            50514
#define IDS_ACC_MARK_EXIST              50515
#define IDS_DB_PATHMISSING              50516
#define IDS_VAL_LENGTH                  50517
#define IDS_VAL_QUANTITY                50518
#define IDS_SUMMARYTITLE                50519
#define IDS_LINE1_OVERFLOW              50520
#define IDS_CEE_PUNCH_MSG               50521
#define IDS_PUNCHPOS_MSG                50522
#define ID_STATIC                       65535

//nrc
#define ID_FILE_TRANSFER2               95536
#define ID_ITEM_TRANSFER2               95537
// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        176
#define _APS_NEXT_COMMAND_VALUE         32845
#define _APS_NEXT_CONTROL_VALUE         1077
#define _APS_NEXT_SYMED_VALUE           104




#endif
#endif
