/////////////////////////////////////////////////////////////////////////////
//  GRIDWIZ 
//  Copyright (c) 1994-1995 McRae Software International, Inc.
//
//	Warning:  This computer program and source code  is  protected by copyright law and
//	international treaties and is the property of McRae Software International, Inc.
//  Unauthorized reproduction or distribution of this program
//	or source,  may result in severe civil and criminal penalties, and will be prosecuted 
//	to the maximum extent possible under law.
/////////////////////////////////////////////////////////////////////////////
#define CellSelectedTRACE   //TRACE
#define CGridViewTRACE   //TRACE
#define DCGridViewTRACE   //TRACE
#define CalcLeftAndRightTRACE   //TRACE
#define CalcPageSizeTRACE  //TRACE
#define CalcTopAndBottomTRACE   //TRACE
#define ClearSelectedCellsTRACE   //TRACE
#define ClearSelectedRectsTRACE   //TRACE
#define CompactGCOTRACE  //TRACE
#define ColVisibleTRACE   //TRACE
#define CopySelRectTRACE   //TRACE
#define CopyViewTRACE   //TRACE
#define CreateFloatingEditCtrlTRACE   //TRACE
#define DBExceptionDlgTRACE   //TRACE
#define DrawGridCellTRACE   //TRACE
#define FixedCell3DTRACE   //TRACE
#define GetCCUnderPtTRACE   //TRACE
#define GetCellRectTRACE   //TRACE
#define GetCellUnderPtTRACE   //TRACE
#define GetClipTextTRACE   //TRACE
#define GetColNdxTRACE   //TRACE
#define GetColWidthTRACE   //TRACE
#define GetDocumentTRACE   //TRACE
#define GetRowColNdxTRACE   //TRACE
#define GetRowHeightTRACE   //TRACE
#define GetRowNdxTRACE   //TRACE
#define GetScrollCmdTRACE  //TRACE
#define GetSelectedRectTRACE   //TRACE
#define GetSelectionTRACE   //TRACE
#define GetTextRectTRACE   //TRACE
#define GetTextRectTRACE   //TRACE
#define GridDrawFocusRectTRACE   //TRACE
#define GWShowScrollBarTRACE //TRACE
#define InitializeColWidthsTRACE   //TRACE
#define InvalidateCellAllPanesTRACE   //TRACE
#define InvertSelectionTRACE   //TRACE
#define IsColumnHiddenTRACE   //TRACE
#define IsRowHiddenTRACE   //TRACE
#define MoveFloatingEditCtrlTRACE   //TRACE
#define GridOnBeginPrintingTRACE   //TRACE
#define OnBeginPrintingTRACE   //TRACE
#define OnCellChangeTRACE   //TRACE
#define OnChangeColWidthTRACE   //TRACE
#define GridOnChangeFloatingEditTRACE   //TRACE
#define OnChangeFloatingEditTRACE   //TRACE
#define OnChangeRowHeightTRACE   //TRACE
#define GridOnDestroyTRACE   //TRACE
#define OnDestroyTRACE   //TRACE
#define GridOnDrawTRACE   //TRACE
#define OnDrawTRACE   //TRACE
#define GridOnEditCopyTRACE   //TRACE
#define OnEditCopyTRACE   //TRACE
#define GridOnEndPrintingTRACE   //TRACE
#define OnEndPrintingTRACE   //TRACE
#define GridOnFilePrintTRACE   //TRACE
#define OnFilePrintTRACE   //TRACE
#define GridOnFilePrintPreviewTRACE   //TRACE
#define OnFilePrintPreviewTRACE   //TRACE
#define OnGetCellTextTRACE   //TRACE
#define OnGetFixedCellTextTRACE   //TRACE
#define OnGetRecordSetTextTRACE   //TRACE
#define OnHighlightCurrentCellTRACE   //TRACE
#define OnHighlightSelectionTRACE   //TRACE
#define GridOnHScrollTRACE   //TRACE
#define OnHScrollTRACE   //TRACE
#define GridOnInitialUpdateTRACE   //TRACE
#define OnInitialUpdateTRACE   //TRACE
#define GridOnKeyDownTRACE   //TRACE
#define OnKeyDownTRACE   //TRACE
#define GridOnLButtonDownTRACE  //TRACE
#define OnLButtonDownTRACE   //TRACE
#define GridOnLButtonUpTRACE   //TRACE
#define OnLButtonUpTRACE   //TRACE
#define GridOnMouseMoveTRACE   //TRACE
#define OnMouseMoveTRACE   //TRACE
#define GridOnPaintTRACE   //TRACE
#define OnPaintTRACE   //TRACE
#define GridOnPrepareDCTRACE   //TRACE
#define OnPrepareDCTRACE   //TRACE
#define GridOnPreparePrintingTRACE   //TRACE
#define OnPreparePrintingTRACE   //TRACE
#define GridOnPrintTRACE   //TRACE
#define OnPrintTRACE   //TRACE
#define OnSelectionChangeTRACE   //TRACE
#define GridOnSizeTRACE   //TRACE
#define OnSetRecordSetTextTRACE //TRACE
#define OnSizeTRACE   //TRACE
#define GridOnTimerTRACE   //TRACE
#define OnTimerTRACE   //TRACE
#define GridOnVScrollTRACE   //TRACE
#define OnVScrollTRACE   //TRACE
#define PreCreateWindowTRACE   //TRACE
#define PrepareGridCellTRACE   //TRACE
#define RowVisibleTRACE   //TRACE
#define RecalcGridLayoutTRACE //TRACE
#define ScrollAllPanesTRACE   //TRACE
#define SelectTRACE   //TRACE
#define SelectColTRACE //TRACE
#define SelectionCellsTRACE   //TRACE
#define SelectRowTRACE //TRACE
#define SetCellDlgTRACE   //TRACE
#define SetCellAllPanesTRACE   //TRACE
#define SetColWidthTRACE   //TRACE
#define SetCurCellTRACE   //TRACE
#define SetExtentsTRACE   //TRACE
#define SetFixedColumnsTRACE   //TRACE
#define SetFixedRowsTRACE   //TRACE
#define SetGridFontTRACE   //TRACE
#define SetGridOptionsTRACE   //TRACE
#define SetGridScrollRangeTRACE   //TRACE
#define SetMaxRowsTRACE   //TRACE
#define SetMaxColumnsTRACE   //TRACE
#define SetMinColumnTRACE   //TRACE
#define SetMinRowTRACE   //TRACE
#define SetProportionalColWidthsTRACE //TRACE
#define SetRowHeightTRACE   //TRACE
#define ShowColumnTRACE   //TRACE
#define ShowRowTRACE   //TRACE
#define ResizeParentToGridTRACE   //TRACE
#define SmartInvertAllPanesTRACE   //TRACE
#define SmartInvertSelectionTRACE   //TRACE
#define UpdateAllPanesTRACE   //TRACE
#define UpdateDrawingToolsTRACE   //TRACE
#define UpdateCurrentCellStateTRACE   //TRACE
#define CCellContextTRACE   //TRACE
#define SetCCTRACE   //TRACE
#define CGridDCTRACE   //TRACE






